# -*- coding: utf-8 -*-
"""Covid19Kerala.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BWW8BfCjOUfXOycFhoqJAywqCQH6DLCD
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from google.colab import drive 
drive.mount('/content/gdrive')

dataset = pd.read_csv('gdrive/My Drive/Covid Cases Prediction/Confirmed Covid 19 Cases Kerala.csv')
X = []
for i in range(0, len(dataset['Date'])):
  X.append(i)
X = np.asarray(X)
X = X.reshape(-1,1)
y = dataset.iloc[:,-1].values

print(X)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 6)
X_poly = poly_reg.fit_transform(X)
lin_reg = LinearRegression()
lin_reg.fit(X_poly, y)

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, color = 'red')
plt.plot(X_grid, lin_reg.predict(poly_reg.fit_transform(X_grid)), color = 'blue')
plt.title('Covid-19 Cases')
plt.xlabel('Days')
plt.ylabel('Cases')
plt.show()

lin_reg_2.predict(poly_reg.fit_transform([[500]]))